<!doctype html>
<html>
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<link href='http://fonts.googleapis.com/css?family=Open+Sans:400italic,400,700' rel='stylesheet' type='text/css'>
<link href="main.css" rel="stylesheet" type="text/css">
<title>JSON Mail Access Protocol Specification (JMAP)</title>
</head>
<body>
<header>
<div id="logo">JMAP</div>
<ul id="nav">
    <li class="nav-item"><a class="nav-link" href="index.html">Intro</a></li>
    <li class="nav-item"><a class="nav-link" href="spec.html">The Spec</a> </li>
    <li class="nav-item"><a class="nav-link" href="client.html">Using JMAP</a></li>
    <li class="nav-item"><a class="nav-link" href="server.html">Implementing JMAP</a></li>
</ul>
<a href="https://github.com/neilj/jmap"><img style="position: absolute; top: 0; right: 0; border: 0;" src="https://s3.amazonaws.com/github/ribbons/forkme_right_darkblue_121621.png" alt="Fork me on GitHub"></a>
</header>
<article>
